global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/prometheus_rules.yml"
  - "/etc/prometheus/rules/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: "sammy_monitor"
    static_configs:
      - targets: ["sammy_monitor:3000"]
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s