groups:
  - name: sammy_monitor_recording_rules
    interval: 30s
    rules:
      # Uptime calculations over different time periods
      - record: monitor_uptime_5m
        expr: |
          (
            rate(http_monitor_requests_total{status="success"}[5m]) /
            rate(http_monitor_requests_total[5m])
          ) * 100
        labels:
          rule_type: "uptime"

      - record: monitor_uptime_1h
        expr: |
          (
            rate(http_monitor_requests_total{status="success"}[1h]) /
            rate(http_monitor_requests_total[1h])
          ) * 100
        labels:
          rule_type: "uptime"

      - record: monitor_uptime_24h
        expr: |
          (
            rate(http_monitor_requests_total{status="success"}[24h]) /
            rate(http_monitor_requests_total[24h])
          ) * 100
        labels:
          rule_type: "uptime"

      - record: monitor_uptime_7d
        expr: |
          (
            rate(http_monitor_requests_total{status="success"}[7d]) /
            rate(http_monitor_requests_total[7d])
          ) * 100
        labels:
          rule_type: "uptime"

      # Response time percentiles
      - record: monitor_response_time_p50
        expr: |
          histogram_quantile(0.50, 
            rate(http_monitor_response_time_seconds_bucket[5m])
          )
        labels:
          rule_type: "response_time"
          percentile: "50"

      - record: monitor_response_time_p95
        expr: |
          histogram_quantile(0.95, 
            rate(http_monitor_response_time_seconds_bucket[5m])
          )
        labels:
          rule_type: "response_time"
          percentile: "95"

      - record: monitor_response_time_p99
        expr: |
          histogram_quantile(0.99, 
            rate(http_monitor_response_time_seconds_bucket[5m])
          )
        labels:
          rule_type: "response_time"
          percentile: "99"

      # Error rates
      - record: monitor_error_rate_5m
        expr: |
          (
            rate(http_monitor_requests_total{status="failure"}[5m]) /
            rate(http_monitor_requests_total[5m])
          ) * 100
        labels:
          rule_type: "error_rate"

      - record: monitor_error_rate_1h
        expr: |
          (
            rate(http_monitor_requests_total{status="failure"}[1h]) /
            rate(http_monitor_requests_total[1h])
          ) * 100
        labels:
          rule_type: "error_rate"

      # Request rates
      - record: monitor_request_rate_5m
        expr: |
          rate(http_monitor_requests_total[5m])
        labels:
          rule_type: "request_rate"

      # Average response time
      - record: monitor_avg_response_time_5m
        expr: |
          rate(http_monitor_response_time_seconds_sum[5m]) /
          rate(http_monitor_response_time_seconds_count[5m])
        labels:
          rule_type: "avg_response_time"

      # SLA compliance (monthly - 30 days)
      - record: monitor_sla_monthly
        expr: |
          (
            rate(http_monitor_requests_total{status="success"}[30d]) /
            rate(http_monitor_requests_total[30d])
          ) * 100
        labels:
          rule_type: "sla"
          period: "monthly"

      # Current service status (1 = up, 0 = down)
      - record: monitor_current_status
        expr: |
          http_monitor_up
        labels:
          rule_type: "status"